export const BUSINESS_TYPES = [
    { id: 'cat_restaurants', emoji: '🍽️' },
    { id: 'cat_grocery', emoji: '🛒' },
    { id: 'cat_electronics', emoji: '📱' },
    { id: 'cat_health_beauty', emoji: '💄' },
    { id: 'cat_pharmacy', emoji: '💊' },
    { id: 'cat_pets', emoji: '🐾' },
    { id: 'cat_fragrance', emoji: '🌺' },
    { id: 'cat_toys_kids', emoji: '🧸' },
    { id: 'cat_stationery', emoji: '✏️' },
    { id: 'cat_flowers', emoji: '💐' },
    { id: 'cat_home_garden', emoji: '🌿' },
    { id: 'cat_fashion', emoji: '👗' },
    { id: 'cat_other', emoji: '📦' },
];

// ── Category lists per business type ──
export const TEMPLATE_CATEGORIES = {
    cat_restaurants: [
        { en: 'Coffee', ar: 'قهوة' },
        { en: 'Hot Drinks', ar: 'مشروبات ساخنة' },
        { en: 'Iced Drinks', ar: 'مشروبات باردة' },
        { en: 'Fresh Juice', ar: 'عصير طازج' },
        { en: 'Soft Drinks', ar: 'مشروبات غازية' },
        { en: 'Water', ar: 'مياه' },
        { en: 'Breakfast', ar: 'فطور' },
        { en: 'Appetizers', ar: 'مقبلات' },
        { en: 'Salads', ar: 'سلطات' },
        { en: 'Sandwiches', ar: 'سندوتشات' },
        { en: 'Burgers (Beef)', ar: 'برجر (لحم)' },
        { en: 'Burgers (Chicken)', ar: 'برجر (دجاج)' },
        { en: 'Pizza', ar: 'بيتزا' },
        { en: 'Pasta', ar: 'باستا' },
        { en: 'Main Dishes', ar: 'أطباق رئيسية' },
        { en: 'Desserts', ar: 'حلويات' },
        { en: 'Combo Meals', ar: 'وجبات كومبو' },
        { en: 'Other', ar: 'أخرى' },
    ],
    cat_grocery: [
        { en: 'Dairy & Eggs', ar: 'الألبان والبيض' },
        { en: 'Bakery', ar: 'المخبوزات' },
        { en: 'Fruits & Vegetables', ar: 'الفواكه والخضروات' },
        { en: 'Meat & Poultry', ar: 'اللحوم والدواجن' },
        { en: 'Frozen Food', ar: 'الأغذية المجمدة' },
        { en: 'Pantry Essentials', ar: 'أساسيات المطبخ' },
        { en: 'Beverages', ar: 'المشروبات' },
        { en: 'Sanitary & Cleaning', ar: 'المنظفات والأدوات الصحية' },
        { en: 'Other', ar: 'أخرى' },
    ],
    cat_health_beauty: [
        { en: 'Skincare', ar: 'العناية بالبشرة' },
        { en: 'Makeup', ar: 'المكياج' },
        { en: 'Haircare', ar: 'العناية بالشعر' },
        { en: 'Body Care', ar: 'العناية بالجسم' },
        { en: 'Personal Hygiene', ar: 'النظافة الشخصية' },
        { en: 'Other', ar: 'أخرى' },
    ],
    cat_pharmacy: [
        { en: 'Medicine', ar: 'أدوية' },
        { en: 'First Aid', ar: 'إسعافات أولية' },
        { en: 'Vitamins', ar: 'فيتامينات' },
        { en: 'Baby Care', ar: 'العناية بالطفل' },
        { en: 'Personal Care', ar: 'عناية شخصية' },
        { en: 'Other', ar: 'أخرى' },
    ],
    cat_electronics: [
        { en: 'Smartphones', ar: 'هواتف ذكية' },
        { en: 'Tablets', ar: 'أجهزة لوحية' },
        { en: 'Laptops', ar: 'أجهزة لابتوب' },
        { en: 'Gaming', ar: 'ألعاب فيديو' },
        { en: 'Accessories', ar: 'إكسسوارات' },
        { en: 'Chargers', ar: 'شواحن' },
        { en: 'Other', ar: 'أخرى' },
    ],
    cat_pets: [
        { en: 'Dog Food', ar: 'طعام كلاب' },
        { en: 'Cat Food', ar: 'طعام قطط' },
        { en: 'Toys', ar: 'ألعاب' },
        { en: 'Grooming', ar: 'عناية وتنظيف' },
        { en: 'Beds & Carriers', ar: 'أسرة وأقفاص' },
        { en: 'Other', ar: 'أخرى' },
    ],
    cat_fragrance: [
        { en: 'Perfume (Men)', ar: 'عطر رجالي' },
        { en: 'Perfume (Women)', ar: 'عطر نسائي' },
        { en: 'Oud & Bakhoor', ar: 'عود وبخور' },
        { en: 'Gift Sets', ar: 'أطقم هدايا' },
        { en: 'Other', ar: 'أخرى' },
    ],
    cat_toys_kids: [
        { en: 'Baby Essentials', ar: 'لوازم الأطفال' },
        { en: 'Toys', ar: 'ألعاب' },
        { en: 'Educational', ar: 'ألعاب تعليمية' },
        { en: 'Kids Clothing', ar: 'ملابس أطفال' },
        { en: 'School Supplies', ar: 'لوازم مدرسية' },
        { en: 'Other', ar: 'أخرى' },
    ],
    cat_stationery: [
        { en: 'Office Supplies', ar: 'لوازم مكتبية' },
        { en: 'Paper & Notebooks', ar: 'ورق ودفاتر' },
        { en: 'Writing Tools', ar: 'أدوات كتابة' },
        { en: 'Art Supplies', ar: 'أدوات فنية' },
        { en: 'Other', ar: 'أخرى' },
    ],
    cat_flowers: [
        { en: 'Bouquets', ar: 'باقات' },
        { en: 'Box Arrangements', ar: 'تنسيقات في علب' },
        { en: 'Single Stems', ar: 'ورد مفرد' },
        { en: 'Plants', ar: 'نباتات' },
        { en: 'Gifts', ar: 'هدايا' },
        { en: 'Other', ar: 'أخرى' },
    ],
    cat_home_garden: [
        { en: 'Indoor Plants', ar: 'نباتات داخلية' },
        { en: 'Outdoor Plants', ar: 'نباتات خارجية' },
        { en: 'Pots & Planters', ar: 'أواني زراعية' },
        { en: 'Gardening Tools', ar: 'أدوات حديقة' },
        { en: 'Outdoor Decor', ar: 'ديكور خارجي' },
        { en: 'Other', ar: 'أخرى' },
    ],
    cat_fashion: [
        { en: 'Mens Clothing', ar: 'ملابس رجالية' },
        { en: 'Womens Clothing', ar: 'ملابس نسائية' },
        { en: 'Kids Clothing', ar: 'ملابس أطفال' },
        { en: 'Shoes', ar: 'أحذية' },
        { en: 'Bags & Wallets', ar: 'حقائب ومحافظ' },
        { en: 'Accessories', ar: 'إكسسوارات' },
        { en: 'Watches', ar: 'ساعات' },
        { en: 'Jewelry', ar: 'مجوهرات' },
        { en: 'Other', ar: 'أخرى' },
    ],
    cat_other: [
        { en: 'General Items', ar: 'أصناف عامة' },
        { en: 'Kitchen', ar: 'مطبخ' },
        { en: 'Home Decor', ar: 'ديكور منزلي' },
        { en: 'Gifts', ar: 'هدايا' },
        { en: 'Miscellaneous', ar: 'متنوعات' },
        { en: 'Other', ar: 'أخرى' },
    ],
};

// ── Add-on configuration per business type ──
export const TEMPLATE_ADDONS = {
    cat_restaurants: { enabled: true, exampleEn: 'Extra Cheese', exampleAr: 'جبنة إضافية', examplePrice: '+3 QAR' },
    cat_grocery: { enabled: false },
    cat_electronics: { enabled: true, exampleEn: 'Extended Warranty', exampleAr: 'ضمان ممتد', examplePrice: '+50 QAR' },
    cat_health_beauty: { enabled: false },
    cat_pharmacy: { enabled: false },
    cat_pets: { enabled: true, exampleEn: 'Large Size', exampleAr: 'حجم كبير', examplePrice: '+5 QAR' },
    cat_fragrance: { enabled: false },
    cat_toys_kids: { enabled: true, exampleEn: 'Age 3-5', exampleAr: 'عمر ٣-٥', examplePrice: '+0 QAR' },
    cat_stationery: { enabled: false },
    cat_flowers: { enabled: true, exampleEn: 'With Card', exampleAr: 'مع بطاقة', examplePrice: '+5 QAR' },
    cat_home_garden: { enabled: true, exampleEn: 'With Pot', exampleAr: 'مع أصيص', examplePrice: '+15 QAR' },
    cat_fashion: { enabled: true, exampleEn: 'Size: XL', exampleAr: 'قياس: XL', examplePrice: '+0 QAR' },
    cat_other: { enabled: true, exampleEn: 'Variant A', exampleAr: 'النوع أ', examplePrice: '+0 QAR' },
};

// ── Example placeholder items per business type ──
export const TEMPLATE_EXAMPLES = {
    cat_restaurants: { nameEn: 'Spanish Latte Hot', nameAr: 'لاتيه إسباني ساخن', descEn: 'Rich espresso with steamed milk', descAr: 'إسبريسو غني مع حليب مبخر', price: '22' },
    cat_grocery: { nameEn: 'Fresh Milk 1L', nameAr: 'حليب طازج ١ لتر', descEn: 'Full fat fresh milk', descAr: 'حليب طازج كامل الدسم', price: '7.5' },
    cat_electronics: { nameEn: 'Wireless Earbuds', nameAr: 'سماعات لاسلكية', descEn: 'Bluetooth 5.3', descAr: 'بلوتوث ٥.٣', price: '199' },
    cat_health_beauty: { nameEn: 'Hydrating Serum', nameAr: 'سيروم مرطب', descEn: 'Hyaluronic acid for skin', descAr: 'حمض الهيالورونيك للبشرة', price: '85' },
    cat_pharmacy: { nameEn: 'Vitamin C Tablets', nameAr: 'حبوب فيتامين سي', descEn: '1000mg immune support', descAr: '١٠٠٠ ملجم لدعم المناعة', price: '45' },
    cat_pets: { nameEn: 'Dog Food 2kg', nameAr: 'طعام كلاب ٢ كجم', descEn: 'Premium dry food', descAr: 'طعام جاف فاخر', price: '45' },
    cat_fragrance: { nameEn: 'Oud Mood Perfume', nameAr: 'عطر عود مود', descEn: 'Long lasting oriental scent', descAr: 'رائحة شرقية تدوم طويلاً', price: '150' },
    cat_toys_kids: { nameEn: 'Educational Puzzle', nameAr: 'بازل تعليمي', descEn: 'Wooden puzzle for ages 3+', descAr: 'بازل خشبي لعمر ٣+', price: '55' },
    cat_stationery: { nameEn: 'Ballpoint Pens Set', nameAr: 'طقم أقلام حبر', descEn: 'Pack of 10 blue pens', descAr: 'طقم ١٠ أقلام زرقاء', price: '15' },
    cat_flowers: { nameEn: 'Red Roses Bouquet', nameAr: 'باقة ورد أحمر', descEn: '12 fresh red roses', descAr: '١٢ وردة حمراء طازجة', price: '120' },
    cat_home_garden: { nameEn: 'Indoor Plant', nameAr: 'نبتة داخلية', descEn: 'Low-maintenance pothos', descAr: 'نبتة بوتس سهلة العناية', price: '35' },
    cat_fashion: { nameEn: 'Cotton T-Shirt', nameAr: 'تي شيرت قطني', descEn: '100% organic cotton', descAr: 'قطن عضوي ١٠٠٪', price: '99' },
    cat_other: { nameEn: 'Sample Item', nameAr: 'منتج تجريبي', descEn: 'Brief description', descAr: 'وصف مختصر', price: '10' },
};
